name: Regression Test - AT23

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * 1-5'
jobs:
    at23:
      permissions:
        contents: read
      uses: ./.github/workflows/regression-test-ATX.yml
      with:
        environment: AT23
      secrets: inherit