name: Regression Test - AT24

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5'

jobs:
  at24:
    permissions:
      contents: read
    uses: ./.github/workflows/regression-test-ATX.yml
    with:
      environment: AT24
    secrets: inherit
