name: Send Slack Warning

on:
  workflow_call:
    inputs:
      warning-message:
        required: true
        type: string
        description: 'The warning message to include in the Slack notification'
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify-warning-on-slack:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": ":warning: ${{ inputs.warning-message }} :warning: \n\n Workflow available here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
